<?php
namespace app\admin\controller;
use think\Db;
use think\config;
class Index extends AdminBase
{
    // 初始化方法
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 加载驱动页
     * @return mixed
     */
    public function index()
    {
        return $this->fetch();
    }

    public function main()
    {
        return $this->fetch('main',[
            'data' => $this->getMainData()
        ]);
    }

    protected function getMainData()
    {
        $member_total = Db::name('member')->count();
        $common_user_count = Db::name('member')->where(['member_class' => 1])->count();
        $vip_user_count = Db::name('member')->where(['member_class' => 2])->count();
        $gjvip_user_count = Db::name('member')->where(['member_class' => 3])->count();
        $sever_user_count = Db::name('member')->where(['member_class' => 4])->count();
        $terrace_money_total = Db::name('pay_log')->where(['pay_status' => 2])->sum('money');
        // 平台支出 包括2个部分 一个任务 一个会员充值 其实都在佣金
        $expend_money_total = Db::name('hire_log')->where(['is_check' => 1])->sum('hire_money');
        $task_count = Db::name('task')->where('task_id','>',0)->count();
        return [
            'member_total' => $member_total,
            'common_user_count' => $common_user_count,
            'vip_user_count' => $vip_user_count,
            'gjvip_user_count' => $gjvip_user_count,
            'sever_user_count' => $sever_user_count,
            'terrace_money_total' => number_format($terrace_money_total, 2, ',', ' '),
            'expend_money_total' => number_format($expend_money_total, 2, ',', ' '),
            'task_count' => $task_count
        ];
    }
}
