<?php
namespace app\admin\controller;
use think\Controller;
use think\Session;
use think\Db;
class Login extends Controller
{
    // 设置一个路口url跳转
    protected $entranceUrl;

    // 初始化方法
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->entranceUrl = $this->request->baseFile();
        $this->assign([
            'entranceUrl' => $this->entranceUrl
        ]);
    }

    // 登录页
    public function index()
    {
        if (isLogin()) $this->redirect($this->entranceUrl . "/index");
        return $this->fetch();
    }

    /**
     * ajax处理登录
     */
    public function sendLogin()
    {
        if ($this->request->isAjax()) {
            $adminModel = new \app\admin\model\Admin();
            if ($adminModel->sendLogin()) {
                return $this->outJson(0,'登录成功',[
                    'url' => $this->entranceUrl . '/index',
                    'logMsg' => '用户登录'
                ]);
            } else {
                return $this->outJson(1,$adminModel->getError());
            }
        }
    }

    /**
     * 退出登录
     */
    public function loginOut()
    {
        if ($this->request->isAjax()) {
            Session::clear();
            Session::destroy();
            return $this->outJson(0,'退出成功',[
                'url' => $this->entranceUrl . "/login"
            ]);

        }
    }

    /**
     * 输出json数组
     * @param int $code
     * @param string $msg
     * @param array $data
     * @return array
     */
    protected function outJson($code = 0, $msg = '', $data = [])
    {
        if (!$data) {
            return [
                "code" => $code,
                "msg" =>  $msg
            ];
        } else {
            return [
                "code" => $code,
                "msg" =>  $msg,
                "data" => $data
            ];
        }
    }
}