<?php
/**
 * 数据基类
 */
namespace app\common\controller;
use think\Cache;
use think\Controller;
class Base extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }


    /**
     * 输出json数组
     * @param int $code
     * @param string $msg
     * @param array $data
     * @return array
     */
    protected function outJson($code = 0, $msg = '', $data = [])
    {
        if (!$data) {
            return [
                "code" => $code,
                "msg" =>  $msg
            ];
        } else {
            return [
                "code" => $code,
                "msg" =>  $msg,
                "data" => $data
            ];
        }
    }
}
